### ISSUE TITLE
Every item above white quality now has a green border instead of rarity color.

### ISSUE THREAD

**Issue by Bikonito** [StormFX/Masque#11]
They are all colored based on what you have the equipped color set to. I can't find a way to fix this other than disabling the addon.

**Comment by StormFX** [comment]
You'll have to be more specific. What add-on are you using? The author needs to bypass Masque's color override, as stated in the release notes.

**Comment by Restodruid** [comment]
Getting the same problem addon I'm seeing the issue with is bagnon Have told them about the update and copied and pasted the info about Masque's color override

**Comment by StormFX** [comment]
Thanks for letting me know which add-on is doing it. I'll make sure to let them know

**Comment by StormFX** [comment]
On second thought, I'll be reverting this change and requiring action button add-ons to explicitly declare themselves as such. Should be up in < 24 hours. I apologize for the annoyance. Just disable the affected groups in Masque until then.

**Comment by Bikonito** [comment]
Thanks!

**Comment by StormFX** [comment]
Fixed. :p
