### ISSUE TITLE
Masque 1 pixel black border

### ISSUE THREAD

**Issue by SuperNoodlePlays** [StormFX/Masque#26]
After installing masque I get this one pixel black border around my weakauras. Any clue how to disable it?

![image](https://user-images.githubusercontent.com/37938058/39405555-4eccd4d8-4ba7-11e8-8130-17775840b96f.png)

**Comment by StormFX** [comment]
Check various settings in WA. This isn't a Masque issue.

**Comment by Marving1023** [comment]
Try this https://github.com/StormFX/Masque/issues/24

**Comment by StormFX** [comment]
This issue is due to improper settings in WeakAuras and/or ElvUI. Closing.
