### ISSUE TITLE
Help Bartender / masque

### ISSUE THREAD

**Issue by Raismoter** [StormFX/Masque#28]
hi first put the error

Message: ...\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:68: attempt to call method 'CreateTitleRegion' (a nil value)
Time: Sat Jul 21 15:13:52 2018
Count: 1
Stack: ...\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:68: attempt to call method 'CreateTitleRegion' (a nil value)
...\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:68: in function `Initialize'
...\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:662: in function <...\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:656>

Locals: self = <table> {
 Activate = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:265
 EventButton = <unnamed> {
 }
 Deactivate = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:290
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:224
 Toggle = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:248
 L = <table> {
 }
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 Set = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:336
 ToShortKey = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:375
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:231
 RegisterCallback = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 IsShown = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:317
 SetColorKeyBoundMode = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:192
 UnregisterCallback = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 Initialize = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:46
 events = <table> {
 }
 GetColorKeyBoundMode = <function> defined @Interface\AddOns\LibKeyBound-1.0\LibKeyBound-1.0\LibKeyBound-1.0.lua:219
 colorKeyBoundMode = <table> {
 }
 Binder = <table> {
 }
}
f = KeyboundDialog {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = KeyboundDialog {
 0 = <userdata>
}
(*temporary) = "attempt to call method 'CreateTitleRegion' (a nil value)"
L = <table> {
 Alt = "A"
 Button19 = "B19"
 BindingsHelp = "Hover over a button, then press a key to set its binding.  To clear a button's current keybinding, press %s."
 Backspace = "BS"
 End = "En"
 BASEREVISION = 90092
 CombatBindingsEnabled = "Exiting combat, keybinding mode enabled"
 Button17 = "B17"
 Page Up = "PU"
 CannotBindInCombat = "Cannot bind keys in combat"
 Capslock = "Cp"
 REVISION = 0
 Down Arrow = "Dn"
 Button9 = "B9"
 Disabled = "Bindings mode disabled"
 ClearedBindings = "Removed all bindings from %s"
 NoKeysBoundTip = "No current bindings"
 UnboundKey = "Unbound %s from %s"
 Button25 = "B25"
 Button28 = "B28"
 Button26 = "B26"
 Insert = "Ins"
 Button21 = "B21"
 Page Down = "PD"
 Button30 = "B30"
 Right Arrow = "Rt"
 BindingMode = "Binding Mode"
 Button3 = "B3"
 BoundKey = "Set %s to %s"
 Button20 = "B20"
 ClearTip = "Press Esc to clear all bindings"
 Scroll Lock = "SL"
 Button10 = "B10"
 Button2 = "B2"
 Button24 = "B24"
 Button1 = "B1"
 Button22 = "B22"
 NumPad = "N"
 Ctrl = "C"
 Button7 = "B7"
 Button23 = "B23"
 Up Arrow = "Up"
 Left Arrow = "Lf"
 Button16 = "B16"
 Button8 = "B8"
 Button14 = "B14"
 Button29 = "B29"
 Tab = "Tb"
 Shift = "S"
 Spacebar = "Sp"
 Button4 = "B4"
 Button18 = "B18"
 Enabled = "Bindings mode enabled"
 Num Lock = "NL"
 Mouse Wheel Up = "WU"
 Mouse Wheel Down = "WD"
 Home = "HM"
 Delete = "Del"
 Clear = "Cl"
 Button31 = "B31"
 Button5 = "B5"
 Button15 = "B15"
 Button6 = "B6"
 Button12 = "B12"
 CombatBindingsDisabled = "Entering combat, keybinding mode disabled"
 Button11 = "B11"
 Button13 = "B13"
 Button27 = "B27"
}
_G = <table> {
 UpdateOnBar

**Comment by Raismoter** [comment]
i use masque and bartender since tbc
but now i lost my wtf folder so needed to setup all my addon again
but when try to load masque option nothing appened and an error appeared
then try to delete wtf folder and  loaded only masque addon 
everything work fine than try loaded only bartender and masque 
addon but that error massege  showed again when loaded masque option  
and loaded option only miniman button and debug modality are showed nothing else
can t see bartender and general option for change bar skinn

**Comment by Raismoter** [comment]
ok find a solution 
i m italian than play using italian client
just switch on eng and everything work good
it s possible an update for correct this bug ??
bug only appear on italian client for english everything work fine

**Comment by Raismoter** [comment]
ops sorry wrong error that s a correct error 

Message: Interface\AddOns\Masque\Core\Options.lua:237: bad argument #2 to 'format' (string expected, got no value)
Time: Sat Jul 21 16:01:06 2018
Count: 1
Stack: Interface\AddOns\Masque\Core\Options.lua:237: bad argument #2 to 'format' (string expected, got no value)
[C]: in function `format'
Interface\AddOns\Masque\Core\Options.lua:237: in function `GetOptions'
Interface\AddOns\Masque\Core\Options.lua:131: in function `UpdateOptions'
Interface\AddOns\Masque\Core\Options.lua:77: in function `LoadOptions'
Interface\AddOns\Masque\Masque.lua:106: in function <Interface\AddOns\Masque\Masque.lua:105>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:818: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:639>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
(tail call): ?
Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:22: in function <...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

Locals: <none>

**Comment by StormFX** [comment]
I believe I've located the issue. The translator copy/pasted values between translations and neglected to edit them for context. You can see updated translations here: https://www.wowace.com/projects/masque/localization/languages/95/phrases#193245

Note, the translations that were causing errors were the third and fifth ones. If you wouldn't mind, could you review these translations to make sure they're correct?

**Comment by Raismoter** [comment]
if the correct phrase is the english one the italian translete is correct   ......

**Comment by Raismoter** [comment]
check it
now it s correct

**Comment by StormFX** [comment]
This is related to a faulty translation, which should be fixed in the next version. Closing.
