### ISSUE TITLE
Add the ability to set profile and copy profile settings

### ISSUE THREAD

**Issue by DennisJohnsen** [StormFX/Masque#30]
I am currently trying to finish a new update to my UI, and for this i have a simple setup addon that simply sets a AceDB profile and copy settings from a profile i've made.

My Lua capabilities are very limited, but i managed to get the above behavior working for all addons i use, expect Masque. 

```
local PrankUISetup = {};

local MasqueDB = LibStub("AceAddon-3.0"):GetAddon("Masque");

PrankUISetup.DB = function(addon)
    addon.db:SetProfile(UnitName("player").." - "..GetRealmName());
    addon.db:CopyProfile(ProfileName.."-default", true);
end

PrankUISetup.DB(MasqueDB);
```

This code, which i has just isolated to show an example, is how i do it for other addons.

Can you look into a solution where i can use :SetProfile() and :CopyProfile() for Masque?

Kind Regards
Dennis aka. Prankstar

**Comment by StormFX** [comment]
Grab Masque.lua and drop it in your Masque to make sure you don't run into any issues. Note that for Masque, the two methods, `CopyProfile` and `SetProfile` are access directly through Masque's add-on object and have the exact same signature as their AceDB-3.0 counterparts (they're just secure bridges to those methods).

**Comment by DennisJohnsen** [comment]
Works like a charm Storm. Brilliant work!

**Comment by StormFX** [comment]
Good to hear. Closing.
