### ISSUE TITLE
'Background' tick box greyed out in Zoomed skin

### ISSUE THREAD

**Issue by digitaldave71** [StormFX/Masque#44]
In the 'Zoomed' skin, the tick box for 'Background' is already ticked, but the option is greyed out and can not be changed. This means it is not possible to have a dark background like the other skins for empty parts of the action bars (in a similar way to the default bar option to 'Always show action bars'. Would it be possible to change it so that you can have the dark background for empty slots?

**Comment by StormFX** [comment]
Will be added in the next version.
