### ISSUE TITLE
8.1.0-Alpha no longer skinning borders

### ISSUE THREAD

**Issue by ascott18** [StormFX/Masque#50]
In the alpha, skins with borders are no longer creating the border on target frames. This includes:

- TellMeWhen (https://github.com/ascott18/TellMeWhen) - https://github.com/ascott18/TellMeWhen/issues/1684
- https://github.com/ascott18/Masque-Skinner-Blizz-Buffs
- https://github.com/ascott18/Masque-Skinner-ShadowedUF
- Probably my two other "Masque Skinner" addons as well, although I don't use Pitbull or Zperl and so haven't tested them specifically

TellMeWhen above, ShadowedUF buffs left, Dominos below (which is working correctly); Using skin "Renaitre: Square":
![image](https://user-images.githubusercontent.com/5017521/54495737-e0ce5b00-48a3-11e9-9484-cfa8f85d3f51.png)

**Comment by StormFX** [comment]
Is it just the "Normal" layer that's not being created/skinned? IE, are the groups showing up in Masque's GUI and changing size, etc, when a different skin is selected?

I'll install these add-ons when I get home and see if I can narrow down the issue. I can't think of anything I've changed that would affect only the "Normal" region, but you never know. >.<

**Comment by StormFX** [comment]
Actually, I know what's wrong. I added the "Normal" region to the list of layers to search for and forgot to remove the `... or false` bit on [line 27](https://github.com/StormFX/Masque/blob/f47b65f99e1122039495b51db764282fe8295db7/Core/Groups.lua#L257). Remove the `or false` part on that line and see if that fixes it.

**Comment by StormFX** [comment]
FYI, this is addressed in the next alpha, as I'm rewriting a bunch of the internal code.

**Comment by Desik** [comment]
> FYI, this is addressed in the next alpha, as I'm rewriting a bunch of the internal code. But I'll create a relevant commit to close this, once you've confirmed that it fixes the issue.

This fixed it for me.

**Comment by StormFX** [comment]
This should be fixed in the latest alpha. Closing.
