### ISSUE TITLE
Nil error in Core.lua

### ISSUE THREAD

**Issue by StormFX** [StormFX/Masque#59]
@StormFX just here then, yeah? https://github.com/Stanzilla/nivBuffs/blob/37985f5f785023965eb033fe1fca1d3ec4066c4c/nivBuffs.lua#L275 I tested with checking that `btn` exists but that still errord.

_Originally posted by @Stanzilla in https://github.com/StormFX/Masque/issues/57#issuecomment-481808430_

**Comment by StormFX** [comment]
@Stanzilla

My fault again. Until I push another alpha, go into your local copy of Core\Core.lua and move line 51 up three lines so it looks like this:

```lua
		if type(Button) == "table" then
			Type = Button.GetObjectType and Button:GetObjectType()


			if not Type or not oTypes[Type] then
				Type = nil
			end
			Button.__MSQ_oType = Type
		end
```

I'm assuming you're in the process of updating nivBuffs, because there's some seriously old code in there :p. For example, _Masque_ now saves the skin settings, so lines 1350, 1353, 1356 and 1369-1375 are all obsolete.

**Comment by Stanzilla** [comment]
Ah, okay :D Well I'm not really playing atm so I was hoping I could just do a quick fix, but we'll see if I get bored :)
