### ISSUE TITLE
8.2 Pixel Alignment

### ISSUE THREAD

**Issue by ManagerWoW** [StormFX/Masque#64]
Verison: 8.2.0-Beta
Addons/Skins: Weakauras + Masque

The latest 8.2 version of Masque is causing a 1 pixel misalignment between the cooldown sweep animation and the icon. The 8.1.5-Alpha-3 version is working correctly. This is present with all of the default Masque skins, and is especially bad for the "Classic" skin.

Notice the top part of the icon is showing, as well as the cooldown sweep extending 1 pixel too far down.
[Zoomed skin example](http://manager.heroicstrike.org/20190703_153355.mp4)
[Classic skin example](http://manager.heroicstrike.org/20190703_162103.mp4)

**Comment by StormFX** [comment]
I'll look into it.

**Comment by StormFX** [comment]
What are you using for your samples? I can't see any button being that large. Classic clearly needs to be tweaked, but Zoomed is less than a pixel (everything is set for a 1.0 scale, so increasing the scale will throw it all off).

**Comment by ManagerWoW** [comment]
WeakAuras to help show the problem. The issue is present no matter the size,
[WeakAuras](http://manager.heroicstrike.org/20190704_184225.mp4)
[Bartender](http://manager.heroicstrike.org/20190704_184314.mp4)

**Comment by StormFX** [comment]
Ok. It'll be fixed in the next push.

**Comment by StormFX** [comment]
This should be resolved in the latest beta. Let me know if it's not.
