### ISSUE TITLE
Masque classic

### ISSUE THREAD

**Issue by Horodej** [StormFX/Masque#82]
Hi, after new patch Masque is broken - after login in game, stance bar is broken. Vissible only Battle stance. After disable Masque, problem is gone. Can u fix it ??? Thanks !!! :)

**Comment by StormFX** [comment]
This is an issue with the latest version(s) of ElvUI.

**Comment by Horodej** [comment]
No, ElvUI update to last version 1.19 and problem still exist.

BROKEN BUFFS / DEBUFFS / ACTIONBARS:

# Disable Masque and wait for them to push an update.

**Comment by StormFX** [comment]
As I stated above, ElvUI is the problem.

**Comment by StormFX** [comment]
This issue is related to https://www.tukui.org/forum/viewtopic.php?f=40&t=9602. Closing.
