### ISSUE TITLE
Spec profiles not functioning as expected.

### ISSUE THREAD

**Issue by griddark** [StormFX/Masque#88]
Not limited to but tested with a Death Knight. 
Enabled spec profiles, made 3 profiles Blood for Blood etc. Made blood red, frost blue and unholy green. 
Spec do save, but the color doesn't update on switching spec. 
Saving definitely works as if I change spec log out and back in the color does update to the right color.

**Comment by StormFX** [comment]
I'll look into it.

**Comment by griddark** [comment]
I have no idea how/why but this seems to be fixed without changing anything.... I have no idea why it fixed itself but at some point without updating anything it now switches properly between specs.

**Comment by griddark** [comment]
I closed the issue because out of the blue it started working, but now it's not again... no idea, is there any easy way for me to trouble shoot the issue as it drives me crazy not knowing what's going on.

**Comment by griddark** [comment]
Reopened because I thought it was fixed but it's doing the same thing I'm so confused.

**Comment by StormFX** [comment]
I just tested it and it's working fine on my end. Does it update properly when you manually change specs?

**Comment by griddark** [comment]
I've tested it a lot, and it's switching but it's not saving all the colors which is weird, but it could be caused by the skins so I'm about to test them, but I'm not getting any errors which makes it harder to test. I do have lua errors turned on.

**Comment by griddark** [comment]
So, I've deleted the saved variable file and started from scratch, it seems to be working now. 
I'm going to work towards getting everything how it was before and see if it breaks again. (I found debug mode so I can be more helpful if I can recreate the issue). 

Hopefully it's just a wtf moment. Sorry for wasting your time.

**Comment by StormFX** [comment]
Hope you figure it out.
